// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using StoreRescue.Repositories;
using System;

namespace StoreRescue.Migrations
{
    [DbContext(typeof(ApplicationDBContext))]
    [Migration("20180422155308_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("StoreRescue.Models.Category", b =>
                {
                    b.Property<int>("CategoryID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CategoryDescription");

                    b.Property<string>("CategoryName")
                        .IsRequired();

                    b.Property<DateTime>("CreatedDate");

                    b.Property<DateTime>("ModifiedDate");

                    b.Property<int?>("ModifiedUserUserID");

                    b.HasKey("CategoryID");

                    b.HasIndex("ModifiedUserUserID");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("StoreRescue.Models.Product", b =>
                {
                    b.Property<int>("ProductID")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("CategoryID");

                    b.Property<DateTime>("CreatedDate");

                    b.Property<DateTime>("ModifiedDate");

                    b.Property<int>("ModifiedUserID");

                    b.Property<double>("Price");

                    b.Property<string>("ProductDescription");

                    b.Property<string>("ProductName")
                        .IsRequired();

                    b.HasKey("ProductID");

                    b.HasIndex("CategoryID");

                    b.HasIndex("ModifiedUserID");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("StoreRescue.Models.User", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedDate");

                    b.Property<string>("FirstName");

                    b.Property<string>("LastName");

                    b.Property<DateTime>("ModifiedDate");

                    b.Property<int?>("ModifiedUserUserID");

                    b.Property<string>("UserName");

                    b.HasKey("UserID");

                    b.HasIndex("ModifiedUserUserID");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("StoreRescue.Models.Category", b =>
                {
                    b.HasOne("StoreRescue.Models.User", "ModifiedUser")
                        .WithMany()
                        .HasForeignKey("ModifiedUserUserID");
                });

            modelBuilder.Entity("StoreRescue.Models.Product", b =>
                {
                    b.HasOne("StoreRescue.Models.Category", "category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("StoreRescue.Models.User", "ModifiedUser")
                        .WithMany()
                        .HasForeignKey("ModifiedUserID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("StoreRescue.Models.User", b =>
                {
                    b.HasOne("StoreRescue.Models.User", "ModifiedUser")
                        .WithMany()
                        .HasForeignKey("ModifiedUserUserID");
                });
#pragma warning restore 612, 618
        }
    }
}
